#!/usr/bin/env bash
set -ex

pip install --no-cache-dir "dynamic-foraging-processing[full] @ git+https://github.com/AllenNeuralDynamics/dynamic-foraging-processing.git@08305bccd53f54fb2b8f2b79ffb7827b137495ef"